<a href="https://colab.research.google.com/github/gauravjha201/Machine-learning-basics/blob/main/Random_forest_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Predicting the car price

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [ ]:
df=pd.read_csv("/content/cardekho_imputated.csv",index_col=[0])
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

data cleaning

In [ ]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [ ]:
df.drop('car_name',axis=1,inplace=True)
df.drop('brand',axis=1,inplace=True)

In [ ]:
df.head(
)

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [ ]:
df.tail()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [ ]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [ ]:
#getting all differant types of feature
num_feature=[feature for feature in df.columns if df[feature].dtype!="O"]
print("Number of numeric feature",len(num_feature))
cat_feature=[feature for feature in df.columns if df[feature].dtype=="O"]
print("Number of categorical feature",len(cat_feature))
descrete_feature=[feature for feature in df.columns if len(df[feature].unique())<=25]
print("Number of descrete  feature",len(descrete_feature))
con_feature=[feature for feature in df.columns if feature not in descrete_feature]
print("Number of continues feature",len(con_feature))

Number of numeric feature 7
Number of categorical feature 4
Number of descrete  feature 5
Number of continues feature 6

In [ ]:
x=df.drop(['selling_price'],axis=1)
y=df['selling_price']
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [ ]:
y.head()

0    120000
1    550000
2    215000
3    226000
4    570000
Name: selling_price, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['model']=le.fit_transform(x['model'])

In [ ]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [ ]:
len(x['seller_type'].unique()),len(x['fuel_type'].unique()),len(x['transmission_type'].unique())

(3, 5, 2)

In [ ]:
num_feature=[feature for feature in x.columns if x[feature].dtype!='O']
OneHot_feature=["seller_type","fuel_type","transmission_type"]

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

scaler=StandardScaler()
onehot=OneHotEncoder(drop='first')
preprocessor=ColumnTransformer(
    [
    ("OneHotEncoder",onehot,OneHot_feature),
    ("StandardScaler",scaler,num_feature)
],remainder='passthrough')

x=preprocessor.fit_transform(x)

In [ ]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape

((12328, 14), (3083, 14))

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [ ]:
#create a function to evaluate model
def evaluate_model(true,predicted):
  mse=mean_squared_error(true,predicted)
  rmse=root_mean_squared_error(true,predicted)
  mae=mean_absolute_error(true,predicted)
  r2=r2_score(true,predicted)
  return mae,rmse,r2

In [ ]:
models={
    "LinearRegression":LinearRegression(),
    "Ridge":Ridge(),
    "Lasso":Lasso(),
    "K-Neighbors Regression":KNeighborsRegressor(),
    "Decision Tree":DecisionTreeRegressor(),
    "Random forest":RandomForestRegressor()

}

for i in range(len(models)):
  model=list(models.values())[i]
  model.fit(x_train,y_train)

  # Corrected lines: use x_train and x_test for prediction
  y_pred_train=model.predict(x_train)
  y_pred_test=model.predict(x_test)

  model_train_mae,model_train_rmse,model_train_r2_square=evaluate_model(y_train,y_pred_train)
  model_test_mae,model_test_rmse,model_test_r2_square=evaluate_model(y_test,y_pred_test)
  print(list(models.keys())[i])

  print('Model performance for Training Set')
  print('Root Mean Squared error : ',format(model_train_rmse))
  print('Mean Absolute error : ',format(model_train_mae))
  print('R2 Square : ',format(model_train_r2_square))


  print("-----------------------------------------")

  print('Model performance for Test Set')
  print('Root Mean Squared error : ',format(model_test_rmse))
  print('Mean Absolute error : ',format(model_test_mae))
  print('R2 Square : ',format(model_test_r2_square))


  print("********************************************")

LinearRegression
Model performance for Training Set
Root Mean Squared error :  553855.6665411663
Mean Absolute error :  268101.60708299355
R2 Square :  0.6217719576765959
-----------------------------------------
Model performance for Test Set
Root Mean Squared error :  502543.59302309836
Mean Absolute error :  279618.5794158427
R2 Square :  0.6645109298852006
********************************************
Ridge
Model performance for Training Set
Root Mean Squared error :  553856.3159709624
Mean Absolute error :  268059.80146883125
R2 Square :  0.6217710706848425
-----------------------------------------
Model performance for Test Set
Root Mean Squared error :  502533.8229890289
Mean Absolute error :  279557.21689302754
R2 Square :  0.6645239743566809
********************************************
Lasso
Model performance for Training Set
Root Mean Squared error :  553855.6709544231
Mean Absolute error :  268099.22264981153
R2 Square :  0.6217719516489696
-----------------------------------------
Model performance for Test Set
Root Mean Squared error :  502542.6696378939
Mean Absolute error :  279614.7461034126
R2 Square :  0.6645121627547995
********************************************
K-Neighbors Regression
Model performance for Training Set
Root Mean Squared error :  325885.9831001957
Mean Absolute error :  91430.97014925373
R2 Square :  0.8690541073993072
-----------------------------------------
Model performance for Test Set
Root Mean Squared error :  253071.94275810325
Mean Absolute error :  112672.89166396367
R2 Square :  0.914921682456944
********************************************
Decision Tree
Model performance for Training Set
Root Mean Squared error :  20797.23516567643
Mean Absolute error :  5164.819922128488
R2 Square :  0.9994666998284044
-----------------------------------------
Model performance for Test Set
Root Mean Squared error :  293020.1680011024
Mean Absolute error :  122954.41939669153
R2 Square :  0.8859419556359348
********************************************
Random forest
Model performance for Training Set
Root Mean Squared error :  138617.60338093436
Mean Absolute error :  40185.06759572716
R2 Square :  0.9763082418916125
-----------------------------------------
Model performance for Test Set
Root Mean Squared error :  223479.85810723525
Mean Absolute error :  101358.69772087393
R2 Square :  0.9336550809131933
********************************************

In [ ]:
#initializing few parameter for hyperparameter tuning
knn_params={"n_neighbors":[2,3,10,20,40,50]}
rf_params={"max_depth":[5,8,15,None,10],
           "max_features":[5,7,"auto",8],
           "min_samples_split":[2,8,15,20],
           "n_estimators":[100,200,500,1000]}

In [ ]:
randomcv_models=[("KNN",KNeighborsRegressor(),knn_params),
                 ("RF",RandomForestRegressor(),rf_params)]

In [ ]:
##Hyperparameter Tuning
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
    random.fit(x_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
---------------- Best Params for KNN -------------------
{'n_neighbors': 10}
---------------- Best Params for RF -------------------
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 5, 'max_depth': 15}

In [ ]:
## Retraining the models with best parameters
models = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=500, min_samples_split=2, max_features=5, max_depth=15,
                                                     n_jobs=-1),
     "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=10, n_jobs=-1)

}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print('='*35)
    print('\n')

Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 133397.7491
- Mean Absolute Error: 56019.5208
- R2 Score: 0.9781
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 205788.6781
- Mean Absolute Error: 96974.0916
- R2 Score: 0.9437
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 363465.6927
- Mean Absolute Error: 103489.6090
- R2 Score: 0.8371
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 263849.8119
- Mean Absolute Error: 117481.4548
- R2 Score: 0.9075
===================================